### ISSUE TITLE
Некруто использовать String там, где можно использовать enum или полиморфизм

### ISSUE THREAD

**Issue by Jimilian** [neikila/tp_2015_java_42-development#2]
```
public String getRole() { return isSuperUser?"Admin":"User"; }
```
Это значит, что где-то у вас есть код вида:
```
     if (user.getRole() == "Admin")
           doIt();
     else
           denied();
```
Это не круто, т.к. усложняет рефакторинг и вызывает вопросы, т.к. строки так сравнивать нельзя :)

Предлагаю либо заменить на enum, либо, еще лучше, выделить класс, который характеризует поведение, например:
```
class Role {
     boolean hasAccessToAdminPanel() {
           return false;
     }
}

final class Admin extends Role {
    @Override 
    boolean hasAccessToAdminPanel() {
           return false;
     }
     }
```
Но т.к., возможно, выделение класса еще преждевременно.

**Comment by neikila** [comment]
getRole используется только для того, чтобы можно было вывести роль.
Проверка админ ли пользователь делается следующим образом:

private boolean isSuperUser;
...
public boolean isAdmin() { return isSuperUser; }

**Comment by neikila** [comment]
Мето getRole был создан на случай, если вдруг мне потребуется изменить название роли, так, сделав это в одном месте, я изменю везде.

**Comment by Jimilian** [comment]
Тогда можно переименовать роль из ```getRole()``` в ```getRoleName()```. Ну, и enum отлично превращается в String. Бонус от использования enum - можно посмотреть все честные usage в проекте, а не полнотекстовым поиском.
