### ISSUE TITLE
Из любого цикла можно выйти, если использовать return

### ISSUE THREAD

**Issue by Jimilian** [neikila/tp_2015_java_42-development#6]
```
        // Выполнение перебора
        boolean returnValue = false;
        while (!returnValue && itr.hasNext()) {
            if (itr.next().getLogin().equals(userName)) {
                returnValue = true;
            }
        }
        return returnValue;
```
Для улучшения читаемости нужно заменить на:
```
        // Выполнение перебора
        while (itr.hasNext()) {
            if (itr.next().getLogin().equals(userName)) {
                return true;
            }
        }
        return false;
```

В прицнипе, т.к. мы ничего не модифицируем, можно переделать и на простейший for-each.

**Comment by Jimilian** [comment]
В принципе, же итерирование по карте - нелучшая идея. Лучше сделать пользователя ключем, а сессию - значением. Тогда вы получите хорошее время поиска (внимание вопрос, какое? :) ).

**Comment by neikila** [comment]
O(1) - математическое ожидание (но не гарантированно из-за коллизий).
Данный метод используется только для того, чтобы проверить есть ли уже пользователь в онлайне (присутствует ли он в массиве сессий), и используется только при авторизации пользователя.
Этот же массив (сессий) используется для идентификации пользователя по id сессии получаемого из request, что делается чуть ли не на каждой странице.
Поэтому я решил, оставить предложенные вариант, где ключ сессия.

Касательно такой структуры цикла:
нам на курсе С/С++ рассказывали, что уменьшение количества точек выхода из функций повышает скорость выполнения кода и дает лучшие результаты при статистическом анализе кода, поэтому я ввел такую конструкцию.
Если это неффективно в Java, то приму к сведению и больше так усложнять читабельность не буду =)

**Comment by Jimilian** [comment]
"Преждевременная оптимизация - корень всех бед" (с) Д.К.

Я посмотрел ваш код и не нашел мест, где карта "имя пользователь" - "сессия" была бы хуже, чем карта "сессия" - "пользователь".
